### ISSUE TITLE
Setting certain custom strings not working

### ISSUE THREAD

**Issue by andersu** [Instabug/android-sample#16]
Pretty sure this is not the correct place to report it (please point me in the right direction if it is not), but I am trying to set custom texts and most of them work, but not these two:
`InstabugCustomTextPlaceHolder placeHolder = new InstabugCustomTextPlaceHolder();
placeHoldersMap.put(ADD_EXTRA_SCREENSHOT, "Ta et skjermbilde");
placeHoldersMap.put(ADD_IMAGE_FROM_GALLERY, "Legg til eget bilde");
placeHolder.setPlaceHoldersMap(placeHoldersMap);
Instabug.setCustomTextPlaceHolders(placeHolder);
`

I am guessing these texts are the ones at the bottom of the screen when reporting a bug, originally saying "Take a Screenshot" and "Select Image from Gallery". They do not change when I try setting them, but all other custom texts I've tried setting have worked.

**Comment by DevHossamHassan** [comment]
Hello @andersu,
Our main support channel is to mail us anytime at `support@instabug.com`
But it's ok :) we are glad to help you anytime and anywhere :) 

If you still have a problem with `InstabugCustomTextPlaceHolder ` Please try to use the following snippet
and let me know if it didn't work with you
```java
        InstabugCustomTextPlaceHolder placeHolder = new InstabugCustomTextPlaceHolder();

        HashMap<InstabugCustomTextPlaceHolder.Key, String> placeHoldersMap = new HashMap<>();

        placeHoldersMap.put(ADD_EXTRA_SCREENSHOT, "Ta et skjermbilde");
        placeHoldersMap.put(ADD_IMAGE_FROM_GALLERY, "Legg til eget bilde");
        placeHolder.setPlaceHoldersMap(placeHoldersMap);

        Instabug.setCustomTextPlaceHolders(placeHolder);
```

**Comment by andersu** [comment]
Thanks for the reply @DevHossamHassan 
That's the exact code I am using (+ some more placeHoldersMap.put lines).
I tried running just your snippet now. It doesn't set the texts for "Take a Screenshot" and "Select Image from the Gallery". Try running it yourself and see. Does it work for you?

**Comment by DevHossamHassan** [comment]
Yes it does @andersu,
I tried it before sending you my snippet 
@see 
<img src="https://cloud.githubusercontent.com/assets/6613841/23356458/88058926-fce2-11e6-994c-c92081103c8e.png" width="250">

Are you using the latest version of Instabug SDK which is `4.0.2`?

**Comment by andersu** [comment]
That works. Sorry for not trying that before posting the issue and thanks for your help 👍
