### ISSUE TITLE
RxJava 2

### ISSUE THREAD

**Issue by Gaket** [Instabug/android-sample#17]
Hello!

We use RxJava 2 in our project, but you use RxJava 1. We want to buy Instabug to use in our Ios and Android projects, but this issue stops us from making a decision.

What can we do? I think we even can exclude this file from build, but this will lead to addition 6k methods in apk anyway...

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':bankOK:transformResourcesWithMergeJavaResForBetaNewApiDebug'.
> > com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxjava.properties
>   	File1: /Users/gaket/.gradle/caches/modules-2/files-2.1/io.reactivex.rxjava2/rxjava/2.0.2/cfccdd18cdfbe7b4773d42c9f3512eeafbe5cbf9/rxjava-2.0.2.jar
>   	File2: /Users/gaket/.gradle/caches/modules-2/files-2.1/io.reactivex/rxjava/1.1.9/e4362e62f1ba92e360b197d6d7ffae67e5ecae9a/rxjava-1.1.9.jar

**Comment by joharei** [comment]
We are also unable to use Instabug in our project due to this.

**Comment by DevHossamHassan** [comment]
Hello Gaket and Joharei,
We are currently investigating into this and hopefully shipping a fix for this issue with the upcoming release.

**Comment by joharei** [comment]
Thanks for the response @DevHossamHassan. Is there an ETA on that release?

**Comment by DevHossamHassan** [comment]
Hey @joharei 
We are still investigating into it, we are thinking about creating a custom build based on RxJava2 until we are done. If this makes sense for you please let me know.

**Comment by joharei** [comment]
@DevHossamHassan Absolutely. We are using Instabug in our beta program only, so we're willing to help you try something a little experimental if that's what you mean.

**Comment by DevHossamHassan** [comment]
@joharei Sounds great, So we will work on it and will inform you when we finish (maybe earlier next week).
Thank you @joharei

**Comment by Gaket** [comment]
Great, we would like to help you too)

**Comment by Gaket** [comment]
Hello! Are there any progress yet? Do you need testers?)

**Comment by DevHossamHassan** [comment]
Hello Gaket,
Yes, We are currently working on creating a custom build based on RxJava 2 for you and will get back to you soon.

**Comment by DevHossamHassan** [comment]
Hey @Gaket and @joharei,
We have just released a snapshot based on RxJava2 (v4.0.0-SNAPSHOT).


Please make sure to add this line to your app-level build.gradle file
```gradle
repositories {
    maven {
        //  add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
Cheers

**Comment by DevHossamHassan** [comment]
Hi @Gaket and @joharei 
I just following up with you, have you faced any issues while testing the snapshot version?

**Comment by Gaket** [comment]
Hi @DevHossamHassan 

It is an end of a sprint now and we haven't got time to look at your build, sorry. I will work with it in coming Monday or Tuesday. 

By the way, our Ios team already uses your product and they are quite happy with it.

**Comment by joharei** [comment]
Hi @DevHossamHassan 

We decided to go back to using RxJava 1 in our project in order to get our release going. Will have a look at the snapshot when I have time.

Thanks!

**Comment by Gaket** [comment]
Finally, I took some time from PO to configure testing flavor with connected Instabug and now it works like a charm. Thank you!

**Comment by eygraber** [comment]
Has any progress been made here?

**Comment by tarek360** [comment]
Hi @eygraber if you asking about the custom build based on RxJava2
Please check this [comment](https://github.com/Instabug/android-sample/issues/17#issuecomment-292206228).

**Comment by fleficher** [comment]
Hi @tarek360 we have the same problem too, we're planning to use rxjava2 in our project and this is very annoying.
How is it possible to have it in our custom build too ?

Thank you !

**Comment by joharei** [comment]
We're currently using the latest Instabug (4.2.10) and RxJava 2 without problems.

**Comment by tarek360** [comment]
Hi @fleficher 
Our latest versions are based on RxJava 1, you can use it safely with your project which depends on 
RxJava 2, also you can use our snapshot `(v4.0.0-SNAPSHOT)` which has RxJava 2 as a dependency.

* To use the snapshot based on RxJava 2

Please make sure to add the next lines to your app-level build.gradle file

```gradle
dependencies {
  compile 'com.instabug.library:instabug:4.0.0-SNAPSHOT'
}
```

```gradle
repositories {
    maven {
        //  add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Or**

* Use the last version based on RxJava 1

```gradle
dependencies {
    compile 'com.instabug.library:instabug:4.2.11'
}
```

**Comment by fleficher** [comment]
@tarek360 Thanks for this but if we use this dependency we lose all the customizations we've made in our custom build

**Comment by tarek360** [comment]
Hi @fleficher what's the RxJava problem with the Instabug version which you use?

**Comment by fleficher** [comment]
Hi @tarek360 I've the same problem as the author of this bug if we try to use RxJava2 (used by another dependency in the project)

**Comment by tarek360** [comment]
@fleficher methods count issue or you have a conflict with RxJava 1 ??

**Comment by fleficher** [comment]
@tarek360 conflicts between RxJava 1 & 2

**Comment by tarek360** [comment]
@fleficher that's very easy to fix

You can add the next few lines to your app/build.gradle at:

```gradle
android {
    ...
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
}
```
[reference](https://github.com/ReactiveX/RxJava/issues/4445)

**Comment by fleficher** [comment]
@tarek360 Thanks for the fix but is it planned on your side to migrate to rxjava2 ?
It's very annoying to embed 2 different versions of the same library just for one sdk. It adds thousands of methods in the apk.
Some sdks provides optional dependencies to solve those problems. It would be great to have this.

**Comment by tarek360** [comment]
Hi @fleficher

We have a plan to remove RxJava from our SDK, since we remove it I will notify you. please if you have any issue with that tell me.

Thank you.
