### ISSUE TITLE
API doc not updated for 4.0.1

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#19]
I'm trying to update Instabug library to the latest version 4.0.1, but found that the [API doc](https://dashboard.instabug.com/public/android-api-reference/com/instabug/library/Instabug.html)  is not updated. I don't know details about some functions I want to use. Would you please update the API doc? Thanks!

**Comment by DevHossamHassan** [comment]
Thanks gejiaheng for reporting this,
Without a doubt :) and it  would be great if you mentioned which function you don't know details about?

**Comment by gejiaheng** [comment]
Just details of initialization of Instabug while using `Instabug.Builder`。Say the method 'setAttachmentTypesEnabled()', I don't know what each argument stands for.

**Comment by DevHossamHassan** [comment]
Hey @gejiaheng,
`setAttachmentTypesEnabled()` is used for  Enabling /disabling  the attachment types for Bug and Chat

```java
     Instabug.Builder.setAttachmentTypesEnabled(boolean initialScreenshot, boolean extraScreenshot, boolean galleryImage, boolean voiceNote, boolean screenRecording) ;

```
these params stand for:
```
          @param initialScreenshot weather initial screenshot is enabled or not
          @param extraScreenshot   weather extra screenshot is enabled or not
          @param galleryImage      weather image from gallery is enabled or not
          @param voiceNote         weather voice recording is enabled or not
          @param screenRecording   weather screen recording is enabled or not
```
example 
```java 
  Instabug.Builder.setAttachmentTypesEnabled(true,true,true,true,true) ;
```

<img src="https://cloud.githubusercontent.com/assets/6613841/22873680/398b35fc-f1ca-11e6-9ee5-50e02446c3b0.gif" width="250">

**Comment by gejiaheng** [comment]
Thanks @DevHossamHassan . I found that you also have [integration doc](http://docs.instabug.com/v4/docs/getting-started) that helps a lot. It would be better if you keep all docs updated.

**Comment by DevHossamHassan** [comment]
Sounds great, You are welcome @gejiaheng.
Thanks for your feedback we really appreciate that and I already added a note for updating and adding more details in our APIs docs.
Thanks again :) .
