### ISSUE TITLE
Instabug Library Size -> Future?

### ISSUE THREAD

**Issue by lernerb** [Instabug/android-sample#21]
Hey ya'll. Is there any plan to make a smaller Instabug library? Been using it for a while - but it's seemed to just grow and grow and it's getting bigger every release. At this point it's about 9k methods due to jcodec.

```
\--- com.instabug.library:instabug:4.0.1 `(3701) methods`
     +--- com.android.support:multidex:1.0.1
     +--- io.reactivex:rxjava:1.1.9
     +--- io.reactivex:rxandroid:1.2.0 -> 1.2.1 (*)
     +--- com.android.support:support-v4:24.2.1 (*)
     +--- com.squareup.mimecraft:mimecraft:1.1.1
     \--- org.jcodec:jcodec-android:0.1.9
          \--- org.jcodec:jcodec:0.1.9 `(5205 methods)`
```

**Comment by tarek360** [comment]
Let me ask the team about that, but I want to ask you a question please, do
you face a real problem with the multidex or what?

**Comment by lernerb** [comment]
Hey Tarek - our team is not running into a dex issue - we're just wondering if there is a lightweight version in the works :)

**Comment by lernerb** [comment]
Going to close this since it's not critical right now, and was just a question for the devs 👍

**Comment by sillysachin** [comment]
Instabug seems to be slow and adding to apk size. Can there be a smaller light weight version of it ?
