### ISSUE TITLE
Disable default screen capturing

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#22]
Can I disable default screen capturing when invoking `Instabug.invoke(InstabugInvocationMode.NEW_FEEDBACK)` programmatically? It is a little strange when you just want to get feedbacks about the App, but still with a screenshot of the **Settings** UI.

**Comment by gejiaheng** [comment]
Problem solved!
I invoked `Instabug.setAttachmentTypesEnabled(false, false, false, false, false);` in `OnSdkInvokedCallback`. Now I invoke it earlier and it works as I expected.

**Comment by DevHossamHassan** [comment]
Hello @gejiaheng,
You can disable it by setting `false` to setTttachmentTypesEnabled API in the first parameter which is initialScreenshot boolean that controls whether the initial screenshot is enabled or not.

```java
 new Instabug.Builder(this, "ANDROID_TOKEN")
.setAttachmentTypesEnabled(false, true, true, true, true)
.build();
```

**Comment by gejiaheng** [comment]
@DevHossamHassan Thanks anyway!

**Comment by DevHossamHassan** [comment]
Anytime :)
