### ISSUE TITLE
Infinite loading when sending a feedback

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#23]
The loading bar pops up and doesn't disappear when I try to send a feedback. But it is OK if I am sending a bug.

<img src="https://cloud.githubusercontent.com/assets/3777021/23214151/9aca2c08-f948-11e6-858e-6b60e8c00dc6.png" width="50%" />

Instabug initialization:
```java
new Instabug.Builder((Application) context.getApplicationContext(), BuildConfig.INSTABUG_KEY)
				.setEmailFieldRequired(false)
				.setCommentFieldRequired(false)
				.setInvocationEvent(InstabugInvocationEvent.NONE)
				.setIntroMessageEnabled(false)
				.setCrashReportingState(Feature.State.DISABLED)
				.setTrackingUserStepsState(Feature.State.DISABLED)
				.setAttachmentTypesEnabled(true, true, true, false, true)
				.build();

		if (AccountManager.getInstance().hasAccount()) {
			Instabug.setUserData(AccountManager.getInstance().getCurrentAccount().getUid());
		}
		Instabug.setDebugEnabled(BuildConfig.DEBUG);
```

And I invoke the NEW_FEEDBACK UI programmatically like this:
```java
InstabugLog.clearLogs();
InstabugLog.d(/*some useful info*/);
Instabug.invoke(InstabugInvocationMode.NEW_FEEDBACK);
```

I'm using Instabug Android SDK v4.0.2, and my phone is Nexus 6P, Android 7.1.1.

Thanks!

**Comment by DevHossamHassan** [comment]
Hey @gejiaheng, 
Thank you for reporting this, I will look into it and let you know as soon as we have a fix.

**Comment by gejiaheng** [comment]
@DevHossamHassan Any updates?

**Comment by DevHossamHassan** [comment]
Hey @gejiaheng 
We have just fixed this issue and it will be shipped very soon with the upcoming release!
Thank you so much for your patience.

**Comment by gejiaheng** [comment]
@DevHossamHassan Sounds great!

**Comment by DevHossamHassan** [comment]
Hello @csaba-csete-87,
I believe this issue has been fixed a long time ago.
Is it still exists?
if it is, please don't hesitate to inform us.
