### ISSUE TITLE
Android system chat notification disappears after the second one arrives

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#24]
When there is a new Instabug chat message, a In-App notification would pop up above the App UI. Then a Android system notification would be shown in the phone's notification bar if user doesn't click the In-App notification. It works fine until the second notification arrives. There is still a In-App notification. But the first system notification disappears and nothing left in the notification bar. 

And I tested two scenarios. One is that all message are from the same conversation and the other one is that two messages are from different conversations. Both have triggered the bug.

I'm using Instabug Android SDK v4.0.2, and my phone is Nexus 6P, Android 7.1.1.

Thanks!

**Comment by dirkam** [comment]
+1

**Comment by tarek360** [comment]
@gejiaheng @dirkam Thank you for reporting that, we will check it and get back to you soon.

**Comment by gejiaheng** [comment]
@tarek360 
I test it with the latest SDK 4.0.7, the behavior has changed. There will always one system notification in the status bar. Is this an intended behavior? And it this bug fixed?

**Comment by tarek360** [comment]
Hi @gejiaheng
The behavior is by design so if you have another suggestion you are welcome :)
thanks.

**Comment by gejiaheng** [comment]
@tarek360 
I'm OK with this design!
