### ISSUE TITLE
How to change toolbar's background color?

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#31]
I want to change toolbar's background color to match the App's primary color. Tried `Instabug.setPrimaryColor()` but didn't work. Is it possible?

Instabug Android SDK v4.0.7

**Comment by DevHossamHassan** [comment]
Hello @gejiaheng,
Unfortunately, for now, It's not. 
For customizing the SDK UI We have two themes Light theme and dark theme
you can use them by adding this line to the Instabug Builder `                .setTheme(InstabugColorTheme.InstabugColorThemeLight)` 
and these are the values used in setting the theme`InstabugColorThemeLight`, `InstabugColorThemeDark`  and you can customize also the icons color by using this API 
`Instabug.setPrimaryColor(Color.parseColor("#efca4c"));`

**Comment by DevHossamHassan** [comment]
@gejiaheng By the way, we'll add it to our roadmap and we will let you know when it exactly will be released. 👍 
Regards :)

**Comment by gejiaheng** [comment]
@DevHossamHassan 
Thanks!
