### ISSUE TITLE
Surveys

### ISSUE THREAD

**Issue by joxad** [Instabug/android-sample#36]
Hello InstaTeam,

I am using your project for a few months and I saw you added Surveys. I wanted to test it on Android, but the doc is available only on iOS.

http://docs.instabug.com/docs/surveys

Is it a specific feature? Or can you share some infos in here ?

Thanks a lot :) !

**Comment by tarek360** [comment]
Hi @joxad
Surveys is available on our android SDK starting from version 4.0.1 , so you can go to your account on the Intsabug dashboard, select the android app and create a new survey, then you will receive it on your android app, surely​ I recommend to use the latest version 4.0.10
Thanks.

**Comment by joxad** [comment]
Hi thanks a lot ! I am currently using the snapshot version in order to use Instabug alongside with RxJava 2 (https://github.com/Instabug/android-sample/issues/17) 
When we create a survey, how can I show it into the application ? 

I would like to hide the classic instabug button (in order to keep it only for intern purposes) and I will call the survey myself in order to show it for all users.

**Comment by tarek360** [comment]
@joxad 
Surveys is showing automatically by default, but you can disable the automatic showing
`.setSurveysAutoShowing(false)` then call `Instabug.showValidSurvey()` whenever you want to show it, by the way, you can prevent your users from invoking Instabug by `.setInvocationEvent(InstabugInvocationEvent.NONE)` and this will hide the Instabug floating button.
