### ISSUE TITLE
android.content.res.Resources$NotFoundException (InstabugFeedbackFragment.java:288)

### ISSUE THREAD

**Issue by CAMOBAP795** [Instabug/android-sample#4]
Today I faced with crash inside instabug library

More info here
http://crashes.to/s/0efa7752433

How can I help to fix it?

**Comment by mSobhy90** [comment]
@CAMOBAP795 Can you tell me which version of the SDK are you using? And do you have any reproduction steps for those issues?

**Comment by CAMOBAP795** [comment]
@mSobhy90 

> Can you tell me which version of the SDK are you using?
2.3.1

> And do you have any reproduction steps for those issues?
In my app I use only shake event to activate Instabug feedback form

I have looked at stack trace and looks like instabug library didn't lookup some android.R resource

As you can see form link above http://crashes.to/s/0efa7752433 issues occurs only on old devices (Sony Xperia L 4.2.2, Samsung S3 4.3)

**Comment by mSobhy90** [comment]
@CAMOBAP795 Might be best if you can upgrade to latest version of Instabug and see if that solved your issue or not, currently we are at `2.3.3` which fixes some bugs that existed in `2.3.2`. Please try it out and let me know if you've still got the same issues.

**Comment by CAMOBAP795** [comment]
for sure, give me 2d please

**Comment by r8tin-admin** [comment]
Problem still exists on 2.3.3

**Comment by mSobhy90** [comment]
@r8tin-admin Can you send me the stacktrace for the issue? And any reproduction steps, if you have any?

**Comment by CAMOBAP795** [comment]
http://crashes.to/s/0efa7752433,
Actually no steps this happens occasionally

**Comment by mSobhy90** [comment]
OK @CAMOBAP795 I'll work on reproducing this to see why it happens. Any specifics about the environment? Android Version, Device, etc..?

**Comment by CAMOBAP795** [comment]
All this you can get from link above http://crashes.to/s/0efa7752433

**Comment by mSobhy90** [comment]
I'm sorry @CAMOBAP795 but seems that this isn't using the last version as well 😄 as it's referencing an invalid line.
`audioAttachmentView.findViewById(R.id.instabug_btn_remove_attachment).setTag(attachment);`
Which doesn't include `inflate` as Crashlytics is mentioning, can you please double check this as well :)

**Comment by CAMOBAP795** [comment]
Resolved
