### ISSUE TITLE
First message of a conversation not sent when it's an image

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#41]
Reproduce steps:
1. Click FAB to create a new conversation
2. Select Image from Gallery
3. Send the selected image
4. Nothing happens

This bug only happens when the first message of a conversation is an image. Everything becomes normal when I send a text message as the first one.

Phone: Nexus 6P
Android version: 7.1.2
Instabug SDK: 4.1.1

**Comment by tarek360** [comment]
@gejiaheng Thank you for reporting this and thank you for the full description, I will check it and feedback you.

**Comment by tarek360** [comment]
Hi @gejiaheng 

We have fixed it, and you can use this **SNAPSHOT**

```
compile 'com.instabug.library:instabug:4.1.1.5-SNAPSHOT'
```

Please add this to your app-level build.gradle file to grab snapshots:
```gradle
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by gejiaheng** [comment]
@tarek360 Thanks, I've tested it, it's all fine now.
