### ISSUE TITLE
Unify changelogs / releases

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#43]
I found at least 4 pages about changelog/releases of Instabug Android SDK, and they are:  
- https://github.com/Instabug/android-sample/blob/master/CHANGELOG.md
- https://github.com/Instabug/android-sample/wiki/Changelog
- https://github.com/Instabug/android-sample/wiki/Using-snapshots (Snapshots)
- https://dashboard.instabug.com/applications/zhihu-android/live/sdk/changelog

Maybe it's better to unify these pages.

**Comment by vezikon** [comment]
Hi @gejiaheng, Thank you for the feedback. We will definitely unify those.

**Comment by vezikon** [comment]
Hello @gejiaheng we unified these pages. Please, re-check them again

**Comment by gejiaheng** [comment]
@vezikon Awesome job!
