### ISSUE TITLE
NPE com.instabug.library.dialog.a.onShow (InstabugFrameAnimationDialog.java:86)

### ISSUE THREAD

**Issue by CAMOBAP795** [Instabug/android-sample#5]
Today I faced with crash inside instabug library

More info here
http://crashes.to/s/2aaac5087fc

How can I help to fix it?

**Comment by mSobhy90** [comment]
@CAMOBAP795 This should be fixed in 2.3.2, can you please try it out and tell me if that's the case?

**Comment by CAMOBAP795** [comment]
for sure, give me 2d to verify

**Comment by r8tin-admin** [comment]
Problem still exists on 2.3.3

**Comment by mSobhy90** [comment]
@r8tin-admin Can you send me the stacktrace for your issue?

**Comment by CAMOBAP795** [comment]
The same http://crashes.to/s/2aaac5087fc

**Comment by mSobhy90** [comment]
Hey @CAMOBAP795, this doesn't seem to be using the latest version yet. Might be a user that didn't upgrade the app yet.
As the line mentioned in the stacktrace is:
`if (mAnimatedFrame != null) {`
Which doesn't make sense to throw a NPE 😂

**Comment by CAMOBAP795** [comment]
Let me doublecheck

**Comment by CAMOBAP795** [comment]
My bad, looks like issue doesn't appears any longer I confused by #4 issue
