### ISSUE TITLE
SDK installed successfully but can't find the SDK in Android Studio

### ISSUE THREAD

**Issue by ysyyork** [Instabug/android-sample#53]
Hi, 

I followed this sample to add this in my app's build.gradle file: 
```
compile('com.instabug.library:instabug:4.2.6') {
        // TODO uncomment this line to exclude RxJava from Instabug and use your own version
        exclude group: 'io.reactivex'

        // TODO uncomment next line if you're facing compilation issue in build.gradle about gms different versions
//        exclude group: 'com.android.support'
    }
```
And clicked sync. Everything works well but I can't import Instabug class. It's showing red. And I was looking for this lib in the external libraries but I couldn't find it. However, it's sitting in the ~/.gradle folder. I don't know what's going on here. Anyone can help?

**Comment by ysyyork** [comment]
Sorry, proven to be an android studio issue. Deleted the .idea folder and reopen then it works. Closing this issue

**Comment by tarek360** [comment]
You are welcome at any time :)
