### ISSUE TITLE
java.lang.NoClassDefFoundError: com.instabug.library.analytics.AnalyticsObserver$1

### ISSUE THREAD

**Issue by ysyyork** [Instabug/android-sample#54]
I followed this:
```
compile 'com.instabug.library:instabug:4.2.6'
```
```
new Instabug.Builder(this, "xxxxxxxxxxxxxxxxxxxxxxxx")
                    .setInvocationEvent(InstabugInvocationEvent.SHAKE)
                    .build();
```

 and everything compiled but when I actually called the setInvocationEvent function, it raised this error and I don't know what's going on. I can find AnalyticsObserver class in the sdk.

**Comment by tarek360** [comment]
Hi @ysyyork ,
Thank you for reporting this issue, does it happen with all of the Android API levels?

**Comment by ysyyork** [comment]
Hi @tarek360 THanks for your reply. What do you mean by all of the Android API levels?  I tested just using AnalyticsObserver class. it's raising the same error.

**Comment by ysyyork** [comment]
Sorry, only the AnalyticsObserver.getInstance method will raise this error. If I just declare like 
`AnalyticsObserver observer;`
It won't raise this. So I think this is a runtime issue?

**Comment by tarek360** [comment]
@ysyyork I mean have you tested it on several Android versions? what is Android version which you tested on?

**Comment by ysyyork** [comment]
No, I only tested on my device which runs android 6.0.1

**Comment by tarek360** [comment]
Do you have a lot of dependencies in your project? if yes, please check this https://stackoverflow.com/a/27709640

**Comment by ysyyork** [comment]
Thanks for your reply. I have multidexEnabled before but I didn't extend the MultidexApplication class. however, even by doing so, the same exception is thrown.

**Comment by tarek360** [comment]
@ysyyork Could you send a sample app with the issue, please? It will help us to fix the issue quickly.

**Comment by NadineMansour** [comment]
@ysyyork I am following up on Tarek’s request. I will close the issue, and feel free to reopen it once you have the sample app ready.
