### ISSUE TITLE
ANR beause of InstabugCrashesUploaderService

### ISSUE THREAD

**Issue by samrombswm** [Instabug/android-sample#55]
E/ActivityManager: ANR in com.app.android.internal
                                                  PID: 20706
                                                  Reason: executing service com.app.android.internal/com.instabug.crash.network.InstabugCrashesUploaderService
                                                  Load: 9.25 / 7.69 / 7.74

This is on sdk version 4.2.6

**Comment by samrombswm** [comment]
It appears 4.2.4 is the last version which does not cause this problem

**Comment by DevHossamHassan** [comment]
Hello @samrombswm 
Thank you for reporting this issue, I'm wondering whether you are enabling the pro-guard or not.
and whether you encountering this on the debug or on the release mode. 
Regards.

**Comment by samrombswm** [comment]
Hi @DevHossamHassan this happens on debug and we do not have pro-guard enabled.

**Comment by DevHossamHassan** [comment]
Hey @samrombswm, 
Could you please send me the full stack-trace for this exception?
and Is this happens consistently?

**Comment by randaelbaz** [comment]
Hi @samrombswm 
Is there an update regarding the stack-trace and whether it happens consistently or not?  I will close this issue, for now, please reopen if the problem still persists.
