### ISSUE TITLE
In-App notifications for already read messages appear again.

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#58]
We have some users complaining receiving the same Instabug In-App notification everyday.

Instabug console link: 
https://dashboard.instabug.com/applications/zhihu-android/live/bugs/137030

Instabug SDK version: 4.2.0.5-SNAPSHOT
We've tried to update to a later version, but came across a few different crashes, so we rolled back to the above version.

Would you please find out why this happens? Hope it's server side's problem.

**Comment by randaelbaz** [comment]
Hey Gejiaheng,

I am Randa from Customer Happiness team jumping in for your support. 

We're currently aware of this problem and our Android dev team is working on reproducing this issue and figuring out a fix. Thank you so much for pointing this out. 

I will definitely update you once it's done.

**Comment by reemalashry1** [comment]
Hey @gejiaheng  

This issue is fixed now in version: 4.2.9

**Comment by gejiaheng** [comment]
Thanks! I'll update the SDK in our coming release.
