### ISSUE TITLE
Start bug report from a click event

### ISSUE THREAD

**Issue by linkinamine** [Instabug/android-sample#61]
Is there a way to start a bug report screen with a simple click event : 
for now the possible ways are : 
    NONE,
    SHAKE,
    FLOATING_BUTTON,
    SCREENSHOT_GESTURE,
    TWO_FINGER_SWIPE_LEFT;

**Comment by randaelbaz** [comment]
Hey @linkinamine 

You can easily do that by calling the manual invocation API call `Instabug.invoke();` in your onClick event.  Did you try using this API? 
For more info check this link: https://docs.instabug.com/docs/android-invocation#section-manual-invocation
