### ISSUE TITLE
Instabug.disable cause NullPointerException

### ISSUE THREAD

**Issue by fleficher** [Instabug/android-sample#63]
Hi,

Calling Instabug.disable() after Instabug.enable() cause an NullPointerException in the SDK : 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean rx.Subscription.isUnsubscribed()' on a null object reference
       at com.instabug.library.messaging.b.a.e(SynchronizationManager.java:100)
       at com.instabug.library.messaging.b.a.d(SynchronizationManager.java:120)
       at com.instabug.library.f.x(InstabugDelegate.java:330)
       at com.instabug.library.f.g(InstabugDelegate.java:298)
       at com.instabug.library.Instabug.disable(Instabug.java:762)
```

Using 3.9.2-SNAPSHOT version

**Comment by reemalashry1** [comment]
Hey @fleficher we will be checking this and I'll get back to you 👍

**Comment by reemalashry1** [comment]
Hey @fleficher this issue is fixed in our newer versions, kindly upgrade to the latest version here: 0031190b357cd02b4c8e887b7f200be6c956a4c2

**Comment by fleficher** [comment]
@reemalashry1 Thanks for the update, but the problem is that we're using a custom build so we can't update our sdk to the last version without losing all customizations.
What are the step to follow to keep our build updated ?

**Comment by reemalashry1** [comment]
Hey @fleficher 
No worries, we are working on sending you a snapshot that will have both the customizations you currently have and the fix for the issue.

**Comment by fleficher** [comment]
@reemalashry1 Greet, waiting for the snapshot version :)

**Comment by reemalashry1** [comment]
Hey @fleficher 
we have made a snapshot for you, version 3.9.3-SNAPSHOT

To use the snapshot, please add the next lines to your app-level `build.gradle` file

```dependencies {
 compile 'com.instabug.library:instabug:3.9.3-SNAPSHOT'
}
```

```repositories {
   maven {
       //  add this only if interested in getting SNAPSHOT releases
       url "https://oss.sonatype.org/content/repositories/snapshots"
   }
}
```

**Comment by fleficher** [comment]
Hi @reemalashry1 thank you, bug fixed !
