### ISSUE TITLE
Doesn't capture DialogFragment

### ISSUE THREAD

**Issue by rahatshahzeb** [Instabug/android-sample#7]
Hello guys,

I am unable to capture DialogFragment. May I know the reason why?

Thanks

**Comment by vezikon** [comment]
Have you tried `Instabug.SetDialog(Dialog dialog)`?

**Comment by rahatshahzeb** [comment]
Thanks, missed it.

**Comment by DarushDev** [comment]
I am using version '8.2.2' and cannot find setDialog(Dialog dialog) method. What is the current solution?

**Comment by DarushDev** [comment]
> Have you tried `Instabug.SetDialog(Dialog dialog)`?

I am using version '8.2.2' and setDialog(Dialog dialog) method is deprecated and no longer available. What is the current solution?
