### ISSUE TITLE
Button send is invisible

### ISSUE THREAD

**Issue by fleficher** [Instabug/android-sample#70]
Hello,

Since version 3.9.4-SNAPSHOT, the send button in the top bar is invisible but clickable (hardly).
We're using 3.9.4.1-SNAPSHOT version.

Can you make a patch ? It's a blocking issue for us cause we need to put this version in production soon.

Thank you

**Comment by fleficher** [comment]
Here is a screenshot of what i've :

![sans titre](https://user-images.githubusercontent.com/6464646/32443382-1dfaebdc-c2ff-11e7-9296-825f0888e2a7.png)

**Comment by ZiadAyman** [comment]
@fleficher I am currently communicating the issue with the Android team and will get back to you with the updates.

**Comment by ZiadAyman** [comment]
@fleficher We have fixed the issue and made a snapshot for you that has the fix, kindly use 3.9.4.2-SNAPSHOT. 

Thanks for you patience!

**Comment by fleficher** [comment]
Hi @ZiadAyman It works but now the crash which should be fixed in #65 is occurring again. Why ?

**Comment by ZiadAyman** [comment]
hey @fleficher we have fixed the crash issue for you and we made another snapshot, kindly use version 3.9.4.4-SNAPSHOT

**Comment by fleficher** [comment]
Great, thank you @ZiadAyman
