### ISSUE TITLE
Notifications not showing on API 26 : no channel id

### ISSUE THREAD

**Issue by helmiderbali** [Instabug/android-sample#71]
Hello,

With version `3.9.4-SNAPSHOT` , when i activate push notifications for chat and call method `Instabug.showNotification()` , i do not receive notifications ; instead i get a toast with the message "`Developer warning for package ****** failed to post notification on channel null`".

**Comment by ZiadAyman** [comment]
@helmiderbali Yes I communicated with our Android team and it seems that this issue is occuring with Android 8. We are working on it no worries :) 

We'll be fixing this in our coming release. Meanwhile, we'll send you another Snapshot to use.

**Comment by ZiadAyman** [comment]
@helmiderbali We have fixed the issue and made a snapshot for you that has the fix, kindly use 3.9.4.3-SNAPSHOT.

**Comment by helmiderbali** [comment]
@ZiadAyman I have to report the issue again, as for now version 3.9.4.7-SNAPSHOT, notification channel are not working again. The fix was . not included in newer versions.

`12-07 10:07:51.494 1644-3294/system_process E/NotificationService: No Channel found for pkg=com.venteprivee.debug, channelId=null, id=0, tag=null, opPkg=com.*******, callingUid=10085, userId=0, incomingUserId=0, notificationUid=10085, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
`

**Comment by ZiadAyman** [comment]
@helmiderbali We tested the notifications again and made another build for you. Please try 3.9.4.8-SNAPSHOT and tell me if you still face the same problem.

**Comment by jatney** [comment]
@ZiadAyman hello, so im also facing same problem but mine is in fb before im not seeing this thing pops up but when i update facebook then i started seeing it
![20180826_181719 1](https://user-images.githubusercontent.com/42717840/44629884-4685e480-a95e-11e8-8d04-1151d8fb6184.jpg) this is the screenshot poof and i still recieve notification but limited and its annoying for me pls help me about this. Thank You
