### ISSUE TITLE
SDK dialog appears after screen orientation change.

### ISSUE THREAD

**Issue by 8masterofpuppets8** [Instabug/android-sample#76]
Sometimes the SDK appears when the device is rotated to portrait/landscape instead of when shaked. It becomes quite annoying having to dismiss it all the time on tablet for example.

Here's how I setup the SDK:

```
new Instabug.Builder(GTApplication.getInstance(), TOKEN)
                    .setInvocationEvent(InstabugInvocationEvent.SHAKE)
                    .setCrashReportingState(Feature.State.DISABLED)
                    .build();

Instabug.setIntroMessageEnabled(false);
Instabug.enable();
```

Does the SHAKE event include orientation changes too?

**Comment by ZiadAyman** [comment]
Hey @8masterofpuppets8 
The shake event doesn't include orientation changes no. 
Can you try increasing the invocation threshold so invoking the SDK gets a bit harder, please? 

Tell me please once you try this if it solved the issue or not :)

**Comment by 8masterofpuppets8** [comment]
OK I set it to

`Instabug.setShakingThreshold(600);`

Looks like the orientation change does not trigger the SDK dialog anymore. I can still trigger it by shaking the device so I guess that worked. Thanks!

**Comment by ZiadAyman** [comment]
Perfect. 
Thanks for choosing Instabug :)
