### ISSUE TITLE
instabug internal dependencies should not be transitive

### ISSUE THREAD

**Issue by cerisier** [Instabug/android-sample#79]
Right now, all dependencies from the instabug libary have a `compile` scope where they should have an `implementation` scope.

This is a problem as for instance, we use RxJava2.x but since Instabug declares a `compile` scope dependency to RxJava1.x (and everything else), Android Studio auto imports classes from RxJava1.x.

Are you able to help 👼 ?

![bitmoji](https://render.bitstrips.com/v2/cpanel/dd170274-25c1-457b-a719-aa43e5c5750f-fb222b1c-b292-4103-8c4e-097ed9b7dde9-v1.png?transparent=1&palette=1&width=246)

**Comment by ZiadAyman** [comment]
@cerisier Kindly use 4.10.2.4-SNAPSHOT and let me know how is it going :)
