### ISSUE TITLE
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean 

### ISSUE THREAD

**Issue by dung90it** [Instabug/android-sample#80]
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.instabug.bug.model.Bug.j()' on a null object reference
com.instabug.bug.view.e.h (e.java:303)
com.instabug.bug.view.c.onDoneButtonClicked (c.java:380)
com.instabug.library.core.ui.ToolbarFragment$1.onClick (ToolbarFragment.java:44)
android.view.View.performClick (View.java:6265)
android.view.View$PerformClick.run (View.java:23764)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

**Comment by Korazy** [comment]
@dung90it Hey there, thanks for reporting this. We'll try to get it fixed as soon as possible.

**Comment by Korazy** [comment]
@dung90it can you please let me know which SDK version you're using?
