### ISSUE TITLE
InAppMessaging Ignoring Vibrate Settings

### ISSUE THREAD

**Issue by eygraber** [Instabug/android-sample#84]
If I send a user a message, their device rings even if it is set to only vibrate.

**Comment by Korazy** [comment]
@eygraber Sorry for the late reply. Does this issue occur across multiple different device models and OS versions or only specific ones? Would you also be able to tell me the SDK version you're using?

**Comment by eygraber** [comment]
It occurs on Pixel (8.1.0), Nexus 6 (7), and Nexus 5 (6.0.1). I haven't tried any others. The SDK version is 4.12.1

**Comment by Korazy** [comment]
@eygraber can you please try using com.instabug.library:instabug:4.13.1.5-SNAPSHOT and let me know if it fixes the issue for you?
